# 🏠 ARKA Local Environment Configuration
# Configuración compartida para todos los servicios en ambiente local

# MySQL Database Configuration
spring:
  datasource:
    url: jdbc:mysql://192.168.100.77:3306/arkavalenzuelabd
    username: root
    password: Koke1988****
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
  
  # MongoDB Configuration (local)
  data:
    mongodb:
      uri: mongodb://localhost:27017/arka_notifications
      auto-index-creation: true
  
  # Email Configuration (local/test)
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${ARKA_EMAIL_USERNAME:}
    password: ${ARKA_EMAIL_PASSWORD:}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            trust: smtp.gmail.com

# ARKA Email Settings
arka:
  mail:
    from: noreply@arka.com
    enabled: false

# Eureka Client Configuration
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true

# Management & Actuator
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always

# Logging
logging:
  level:
    root: INFO
    com.arka: DEBUG
    com.arkavalenzuela: DEBUG
    org.springframework.web: INFO
    org.springframework.security: INFO
