# Hello World Service - Local Profile Configuration

server:
  port: 8083

spring:
  application:
    name: hello-world-service

# Eureka
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
    prefer-ip-address: true

# Management
management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

# Logging
logging:
  level:
    com.arka.hello: DEBUG
