# 🏗️ ARKA Config Server Configuration - NATIVE MODE
# Servidor de configuración centralizado usando archivos locales

server:
  port: 8888

spring:
  application:
    name: config-server
  
  # IMPORTANTE: Activar perfil native
  profiles:
    active: native
  
  # Config Server en modo NATIVE (sin Git)
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/config,file:./config-repository,file:../config-repository

# Eureka Client Configuration
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    hostname: localhost
    prefer-ip-address: true

# Management Endpoints
management:
  endpoints:
    web:
      exposure:
        include: health,info,env,configprops,refresh
  endpoint:
    health:
      show-details: always

# Logging
logging:
  level:
    org.springframework.cloud.config: DEBUG
    com.arkavalenzuela: DEBUG
