# Configuración para API Gateway - Entorno Development
server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: cotizador-service
          uri: lb://arca-cotizador
          predicates:
            - Path=/api/cotizador/**
          filters:
            - StripPrefix=2
            
        - id: gestor-solicitudes-service
          uri: lb://arca-gestor-solicitudes
          predicates:
            - Path=/api/gestor/**
          filters:
            - StripPrefix=2
            
        - id: hello-world-service
          uri: lb://hello-world-service
          predicates:
            - Path=/api/hello/**
          filters:
            - StripPrefix=2
            
        # Ruta directa al Eureka Server Dashboard
        - id: eureka-server
          uri: http://localhost:8761
          predicates:
            - Path=/eureka/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,refresh,env,gateway
  endpoint:
    health:
      show-details: always
    gateway:
      enabled: true

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty: INFO
